SELECT M.NOME FROM tbApartamento A join tbMorador M on(A.Morador=M.idMorador)
WHERE A.Numero=003
SELECT VALOR FROM tbCUSTO WHERE Apartamento=002
SELECT CAST(VALOR AS MONEY) FROM tbCUSTO WHERE Apartamento=002
SELECT SUM(CAST(C.VALOR AS MONEY)) FROM tbCusto C WHERE Apartamento=002
EXEC[dbo].[uspACAOCUSTO] 1,2,NULL,NULL,150,0