--PROCEDURE COM AS A플OE NA TABELA APARTAMENTO--
create procedure uspACAOAPARTAMENTO
(
@ACAO INT, --RECEBE INFORMA플O DE QUAL ACAO REALIZAR 0-INSERIR 1-ALTERAR 2-EXCLUIR--
@IDAPARTAMENTO INT=NULL,
@Numero INT,
@Bloco INT,
@Morador INT
)
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN	
			IF(@ACAO=0)
				BEGIN
					INSERT INTO tbApartamento(Numero,Bloco,Morador)
					VALUES (@Numero,@Bloco,@Morador);
				END
			ELSE IF(@ACAO=1)
				BEGIN
					UPDATE tbApartamento SET
					Numero	=@Numero,
					Bloco	=@Bloco,
					Morador	=@Morador
					WHERE idApartamento=@IDAPARTAMENTO;
				END
			ELSE IF(@ACAO=2)
				BEGIN
					DELETE FROM tbApartamento
					WHERE idApartamento=@IDAPARTAMENTO;
				END
			ELSE
				BEGIN
					SELECT ERROR_MESSAGE() AS RETURBO
				END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		SELECT ERROR_MESSAGE() AS RETORNO
	END CATCH
	
END;
--PROCEDURE COM AS A플OE NA TABELA BLOCO--
create procedure uspACAOBLOCO
(
@ACAO INT, --RECEBE INFORMA플O DE QUAL ACAO REALIZAR 0-INSERIR 1-ALTERAR 2-EXCLUIR--
@IDBLOCO INT=NULL,
@DESCRICAO VARCHAR(20),
@CONDOMINIO INT
)
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN	
			IF(@ACAO=0)
				BEGIN
					INSERT INTO tbBloco(Descricao,Condominio)
					VALUES (upper(@DESCRICAO),@CONDOMINIO);
				END
			ELSE IF(@ACAO=1)
				BEGIN
					UPDATE tbBloco SET
					Descricao=upper(@DESCRICAO),
					Condominio=@CONDOMINIO
					
					WHERE idBloco=@IDBLOCO;
				END
			ELSE IF(@ACAO=2)
				BEGIN
					DELETE FROM tbBloco
					WHERE idBloco=@IDBLOCO;
				END
			ELSE
				BEGIN
					SELECT ERROR_MESSAGE() AS RETURBO
				END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		SELECT ERROR_MESSAGE() AS RETORNO
	END CATCH
	
END;
--PROCEDURE COM AS A플OE NA TABELA CONDOMINIO--
create procedure uspACAOCONDOMINIO
(
@ACAO INT, --RECEBE INFORMA플O DE QUAL ACAO REALIZAR 0-INSERIR 1-ALTERAR 2-EXCLUIR--
@IDCONDOMINIO INT=NULL,
@NOME VARCHAR(50),
@ENDERECO VARCHAR(100),
@SINDICO INT
)
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN	
			IF(@ACAO=0)
				BEGIN
					INSERT INTO tbCondominio(Nome, Endereco,Sindico)
					VALUES (upper(@NOME),upper(@ENDERECO),@SINDICO);
				END
			ELSE IF(@ACAO=1)
				BEGIN
					UPDATE tbCondominio SET
					Nome	=upper(@NOME),
					Endereco=upper(@ENDERECO),
					Sindico	=@SINDICO					
					WHERE idCondominio=@IDCONDOMINIO;
				END
			ELSE IF(@ACAO=2)
				BEGIN
					DELETE FROM tbCondominio
					WHERE idCondominio=@IDCONDOMINIO;
				END
			ELSE
				BEGIN
					SELECT ERROR_MESSAGE() AS RETURBO
				END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		SELECT ERROR_MESSAGE() AS RETORNO
	END CATCH
	
END;
--PROCEDURE COM AS A플OE NA TABELA FUNCIONARIO--
create procedure uspACAOFUNCIONARIO
(
@ACAO INT, --RECEBE INFORMA플O DE QUAL ACAO REALIZAR 0-INSERIR 1-ALTERAR 2-EXCLUIR--
@IDFuncionario INT=NULL,
@NOME VARCHAR(50),
@CPF VARCHAR(11),
@RG VARCHAR(11),
@CARGO VARCHAR(20),
@SALARIO varchar(20),
@CONDOMINIO INT
)
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN	
			IF(@ACAO=0)
				BEGIN
					INSERT INTO tbFuncionario(Nome, CPF,RG,Cargo, Salario, Condominio)
					VALUES (upper(@NOME), @CPF, @RG,upper(@CARGO), @SALARIO, @CONDOMINIO);
				END
			ELSE IF(@ACAO=1)
				BEGIN
					UPDATE tbFuncionario SET
					Nome=upper(@NOME),
					CPF=@CPF,
					RG=@RG,
					CARGO=upper(@CARGO),
					Salario=@SALARIO,
					Condominio=@CONDOMINIO					
					WHERE idFuncionario=@IDFuncionario;
				END
			ELSE IF(@ACAO=2)
				BEGIN
					DELETE FROM tbFuncionario
					WHERE idFuncionario=@IDFuncionario;
				END
			ELSE
				BEGIN
					SELECT ERROR_MESSAGE() AS RETURBO
				END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		SELECT ERROR_MESSAGE() AS RETORNO
	END CATCH	
END;
--PROCEDURE COM AS A플OE NA TABELA MORADOR--
create procedure uspACAOMORADOR
(
@ACAO INT, --RECEBE INFORMA플O DE QUAL ACAO REALIZAR 0-INSERIR 1-ALTERAR 2-EXCLUIR--
@IDMORADOR INT=NULL,
@NOME VARCHAR(50),
@CPF VARCHAR(11),
@RG VARCHAR(11)
)
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN	
			IF(@ACAO=0)
				BEGIN
					INSERT INTO tbMorador(Nome, CPF,RG)
					VALUES (upper(@NOME), @CPF, @RG);
				END
			ELSE IF(@ACAO=1)
				BEGIN
					UPDATE tbMorador SET
					Nome=upper(@NOME),
					CPF=@CPF,
					RG=@RG					
					WHERE idMorador=@IDMORADOR;
				END
			ELSE IF(@ACAO=2)
				BEGIN
					DELETE FROM tbMorador
					WHERE idMorador=@IDMORADOR;
				END
			ELSE
				BEGIN
					SELECT ERROR_MESSAGE() AS RETURBO
				END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		SELECT ERROR_MESSAGE() AS RETORNO
	END CATCH	
END;
--PROCEDURE COM AS A플OE NA TABELA CUSTO--
create procedure uspACAOCUSTO
(
@ACAO INT, --RECEBE INFORMA플O DE QUAL ACAO REALIZAR 0-INSERIR 1-ALTERAR 2-EXCLUIR--
@IDCUSTO INT,
@APARTAMENTO INT,
@DESCRICAO VARCHAR(50),
@DATAVENCIMENTO DATE,
@VALOR VARCHAR(20),
@PAGO INT =0
)
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN	
			IF(@ACAO=0)
				BEGIN
					IF(@PAGO=0 OR @PAGO=1)
					BEGIN
						INSERT INTO tbCusto(DataLancamento,Descricao,DataVencimento,Valor,Apartamento,Pago)
						VALUES (GETDATE(),upper(@DESCRICAO),@DATAVENCIMENTO,@VALOR,@APARTAMENTO,@PAGO);
					END
					ELSE
					BEGIN
						ROLLBACK
						SELECT ERROR_MESSAGE() AS RETURBO						
					END
				END
			ELSE IF(@ACAO=1)
				BEGIN
					IF(@PAGO=0 OR @PAGO=1)
					BEGIN
						UPDATE tbCusto SET
						DataLancamento=GETDATE(),
						Descricao	  =upper(@DESCRICAO),
						DataVencimento=@DATAVENCIMENTO,
						Valor		  =@VALOR,
						Apartamento	  =@APARTAMENTO,
						Pago		  =@PAGO						
						WHERE idCusto=@IDCUSTO;
					END
					ELSE
					BEGIN
						ROLLBACK
						SELECT ERROR_MESSAGE() AS RETURBO
					END
				END
			ELSE IF(@ACAO=2)
				BEGIN
					DELETE FROM tbCusto
					WHERE idCusto=@IDCUSTO;
				END
			ELSE
				BEGIN
					SELECT ERROR_MESSAGE() AS RETURBO
				END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		SELECT ERROR_MESSAGE() AS RETORNO
	END CATCH	
END;

